"""BERT-based GAN training pipeline for knowledge-graph fact verification.

Trains a BERTDiscriminator to distinguish real triplets from fakes
generated by swapping entities within the training data.

Usage
-----
    python -m src.gan_trainer --epochs 20 --batch-size 16 --output models/gan
    python -m src.gan_trainer --save-to-db --push-to-mlflow
"""

from __future__ import annotations

import argparse
import logging
import math
import os
import random
import time
from dataclasses import dataclass, field
from typing import Optional

import torch

from factcheck.gan_model import FactGAN
from factcheck.sparql_queries import fetch_mixed_triplets

logger = logging.getLogger(__name__)


# =========================================================================
# Training configuration
# =========================================================================


@dataclass
class GANTrainingConfig:
    lr_d: float = 2e-5
    weight_decay: float = 0.01
    epochs: int = 20
    batch_size: int = 16
    log_every: int = 1
    label_smoothing: float = 0.9

    # Data
    triplets_per_category: int = 500
    categories: Optional[list[str]] = None
    use_synthetic_fallback: bool = True

    # Output
    output_dir: str = "models/gan"
    device: Optional[str] = None


# =========================================================================
# Synthetic fallback data
# =========================================================================

_SYNTHETIC_TRIPLETS: list[tuple[str, str, str]] = [
    ("Paris", "is capital of", "France"),
    ("Berlin", "is capital of", "Germany"),
    ("Tokyo", "is capital of", "Japan"),
    ("London", "is capital of", "United Kingdom"),
    ("Madrid", "is capital of", "Spain"),
    ("Rome", "is capital of", "Italy"),
    ("Ottawa", "is capital of", "Canada"),
    ("Canberra", "is capital of", "Australia"),
    ("Washington D.C.", "is capital of", "United States"),
    ("Beijing", "is capital of", "China"),
    ("Moscow", "is capital of", "Russia"),
    ("Brasilia", "is capital of", "Brazil"),
    ("New Delhi", "is capital of", "India"),
    ("Cairo", "is capital of", "Egypt"),
    ("Buenos Aires", "is capital of", "Argentina"),
    ("Ankara", "is capital of", "Turkey"),
    ("Bangkok", "is capital of", "Thailand"),
    ("Lisbon", "is capital of", "Portugal"),
    ("Vienna", "is capital of", "Austria"),
    ("Stockholm", "is capital of", "Sweden"),
    ("Oslo", "is capital of", "Norway"),
    ("Helsinki", "is capital of", "Finland"),
    ("Athens", "is capital of", "Greece"),
    ("Warsaw", "is capital of", "Poland"),
    ("Dublin", "is capital of", "Ireland"),
    ("Bern", "is capital of", "Switzerland"),
    ("Seoul", "is capital of", "South Korea"),
    ("Nairobi", "is capital of", "Kenya"),
    ("Barack Obama", "was born in", "Honolulu"),
    ("Albert Einstein", "was born in", "Ulm"),
    ("Isaac Newton", "was born in", "Woolsthorpe"),
    ("Marie Curie", "was born in", "Warsaw"),
    ("Leonardo da Vinci", "was born in", "Vinci"),
    ("Wolfgang Amadeus Mozart", "was born in", "Salzburg"),
    ("Mahatma Gandhi", "was born in", "Porbandar"),
    ("Nelson Mandela", "was born in", "Mvezo"),
    ("Charles Darwin", "was born in", "Shrewsbury"),
    ("Nikola Tesla", "was born in", "Smiljan"),
    ("Napoleon Bonaparte", "was born in", "Ajaccio"),
    ("Galileo Galilei", "was born in", "Pisa"),
    ("Pablo Picasso", "was born in", "Malaga"),
    ("Vincent van Gogh", "was born in", "Zundert"),
    ("Ludwig van Beethoven", "was born in", "Bonn"),
    ("Albert Einstein", "has occupation", "Physicist"),
    ("Marie Curie", "has occupation", "Physicist"),
    ("William Shakespeare", "has occupation", "Playwright"),
    ("Leonardo da Vinci", "has occupation", "Painter"),
    ("Isaac Newton", "has occupation", "Mathematician"),
    ("Aristotle", "has occupation", "Philosopher"),
    ("Charles Darwin", "has occupation", "Naturalist"),
    ("Nikola Tesla", "has occupation", "Inventor"),
    ("Pablo Picasso", "has occupation", "Painter"),
    ("Ludwig van Beethoven", "has occupation", "Composer"),
    ("Eiffel Tower", "is located in", "Paris"),
    ("Statue of Liberty", "is located in", "New York"),
    ("Big Ben", "is located in", "London"),
    ("Colosseum", "is located in", "Rome"),
    ("Taj Mahal", "is located in", "Agra"),
    ("Sydney Opera House", "is located in", "Sydney"),
    ("Parthenon", "is located in", "Athens"),
    ("Sagrada Familia", "is located in", "Barcelona"),
    ("Buckingham Palace", "is located in", "London"),
    ("Kremlin", "is located in", "Moscow"),
    ("Louvre Museum", "is located in", "Paris"),
    ("Apple", "was founded in", "1976"),
    ("Microsoft", "was founded in", "1975"),
    ("Google", "was founded in", "1998"),
    ("Amazon", "was founded in", "1994"),
    ("Tesla", "was founded in", "2003"),
    ("Facebook", "was founded in", "2004"),
    ("IBM", "was founded in", "1911"),
    ("Netflix", "was founded in", "1997"),
    ("SpaceX", "was founded in", "2002"),
    ("Wikipedia", "was founded in", "2001"),
    ("William Shakespeare", "wrote", "Hamlet"),
    ("Charles Dickens", "wrote", "Oliver Twist"),
    ("Leo Tolstoy", "wrote", "War and Peace"),
    ("Jane Austen", "wrote", "Pride and Prejudice"),
    ("Homer", "wrote", "Iliad"),
    ("J.K. Rowling", "wrote", "Harry Potter"),
    ("George Orwell", "wrote", "1984"),
    ("Victor Hugo", "wrote", "Les Miserables"),
    ("Herman Melville", "wrote", "Moby Dick"),
    ("Ernest Hemingway", "wrote", "The Old Man and the Sea"),
    ("Albert Einstein", "studied at", "ETH Zurich"),
    ("Barack Obama", "studied at", "Harvard University"),
    ("Isaac Newton", "studied at", "Trinity College"),
    ("Marie Curie", "studied at", "University of Paris"),
    ("Alan Turing", "studied at", "Princeton University"),
    ("Stephen Hawking", "studied at", "University of Oxford"),
]


def _get_synthetic_triplets() -> list[tuple[str, str, str]]:
    triplets = list(_SYNTHETIC_TRIPLETS)
    random.shuffle(triplets)
    return triplets


# =========================================================================
# Metrics tracking
# =========================================================================


@dataclass
class EpochMetrics:
    d_loss: float = 0.0
    d_real_score: float = 0.0
    d_fake_score: float = 0.0
    num_steps: int = 0

    def update(self, step_metrics: dict) -> None:
        self.d_loss += step_metrics["d_loss"]
        self.d_real_score += step_metrics["d_real_score"]
        self.d_fake_score += step_metrics["d_fake_score"]
        self.num_steps += 1

    def average(self) -> dict[str, float]:
        n = max(self.num_steps, 1)
        return {
            "d_loss": self.d_loss / n,
            "d_real_score": self.d_real_score / n,
            "d_fake_score": self.d_fake_score / n,
        }


@dataclass
class TrainingHistory:
    epochs: list[dict[str, float]] = field(default_factory=list)

    def append(self, epoch_avg: dict[str, float]) -> None:
        self.epochs.append(epoch_avg)

    def summary(self) -> dict[str, float]:
        return self.epochs[-1] if self.epochs else {}


# =========================================================================
# GANTrainer
# =========================================================================


class GANTrainer:
    """Train BERTDiscriminator on real vs swap-generated fake triplets."""

    def __init__(
        self,
        config: Optional[GANTrainingConfig] = None,
        triplets: Optional[list[tuple[str, str, str]]] = None,
    ) -> None:
        self.config = config or GANTrainingConfig()

        # Fetch data if not provided
        if triplets is None:
            triplets = self.fetch_training_triplets()
        self.triplets = triplets

        self.gan = FactGAN(
            triplets=triplets,
            device=self.config.device,
        )

        self.optimizer_d = torch.optim.AdamW(
            self.gan.discriminator.parameters(),
            lr=self.config.lr_d,
            weight_decay=self.config.weight_decay,
        )

        self.history = TrainingHistory()

    def fetch_training_triplets(self) -> list[tuple[str, str, str]]:
        triplets: list[tuple[str, str, str]] = []
        logger.info("Fetching training triplets from DBpedia...")
        try:
            triplets = fetch_mixed_triplets(
                per_category=self.config.triplets_per_category,
                categories=self.config.categories,
            )
        except Exception as exc:
            logger.warning("Failed to fetch from DBpedia: %s", exc)

        if len(triplets) < self.config.batch_size and self.config.use_synthetic_fallback:
            logger.warning("Only %d triplets; augmenting with synthetic data.", len(triplets))
            existing = set(triplets)
            for t in _get_synthetic_triplets():
                if t not in existing:
                    triplets.append(t)

        logger.info("Total training triplets: %d", len(triplets))
        return triplets

    def train(
        self,
        epochs: Optional[int] = None,
        save: bool = True,
    ) -> TrainingHistory:
        num_epochs = epochs or self.config.epochs
        batch_size = self.config.batch_size
        triplets = self.triplets

        if not triplets:
            logger.error("No training triplets available. Aborting.")
            return self.history

        num_batches = math.ceil(len(triplets) / batch_size)

        logger.info(
            "Starting training: %d epochs, %d batches/epoch, "
            "batch_size=%d, %d triplets",
            num_epochs, num_batches, batch_size, len(triplets),
        )
        t_start = time.time()

        for epoch in range(1, num_epochs + 1):
            shuffled = list(triplets)
            random.shuffle(shuffled)
            epoch_metrics = EpochMetrics()

            for i in range(num_batches):
                start_idx = i * batch_size
                end_idx = min(start_idx + batch_size, len(shuffled))
                batch = shuffled[start_idx:end_idx]
                if len(batch) < 2:
                    continue

                step_metrics = self.gan.train_step(
                    real_triplets=batch,
                    optimizer_d=self.optimizer_d,
                    label_smoothing=self.config.label_smoothing,
                )
                epoch_metrics.update(step_metrics)

            avg = epoch_metrics.average()
            self.history.append(avg)

            if epoch % self.config.log_every == 0 or epoch == 1:
                elapsed = time.time() - t_start
                # Show some fake examples from last batch
                fake_examples = step_metrics.get("fake_examples", [])
                real_examples = batch[:3]

                logger.info(
                    "Epoch %3d/%d | D_loss: %.4f | D_real: %.3f | D_fake: %.3f | elapsed: %.1fs",
                    epoch, num_epochs,
                    avg["d_loss"], avg["d_real_score"], avg["d_fake_score"],
                    elapsed,
                )
                for real, fake in zip(real_examples, fake_examples):
                    logger.info("  REAL: %s | %s | %s", *real)
                    logger.info("  FAKE: %s | %s | %s", *fake)

        total_time = time.time() - t_start
        logger.info("Training complete in %.1f seconds.", total_time)

        if save:
            self.gan.save(self.config.output_dir)
            logger.info("Model saved to %s", self.config.output_dir)

        return self.history

    def evaluate_triplets(
        self, triplets: list[tuple[str, str, str]]
    ) -> list[dict]:
        scores = self.gan.discriminate_triplets(triplets)
        return [
            {"triplet": t, "score": scores[i].item()}
            for i, t in enumerate(triplets)
        ]


# =========================================================================
# CLI
# =========================================================================


def _push_gan_to_mlflow(output_dir: str, metrics: dict, config: GANTrainingConfig) -> str:
    import dagshub
    import mlflow

    dagshub.init("NLP-Fact-checking", "MarcoSrhl", mlflow=True)
    mlflow.set_experiment("fact-checker")

    run_name = f"gan_swap_ep{config.epochs}"
    with mlflow.start_run(run_name=run_name) as run:
        mlflow.log_artifacts(output_dir, artifact_path="gan_model")
        mlflow.log_params({
            "model_type": "bert-gan-swap",
            "lr_d": config.lr_d,
            "epochs": config.epochs,
            "batch_size": config.batch_size,
        })
        if metrics:
            safe = {k: v for k, v in metrics.items() if isinstance(v, (int, float))}
            mlflow.log_metrics(safe)
        mlflow.set_tag("mlflow.note.content", "BERT GAN with entity-swap generator")
        return run.info.run_id


def main() -> None:
    parser = argparse.ArgumentParser(description="Train FactGAN (swap) on DBpedia triplets.")
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--lr-d", type=float, default=2e-5)
    parser.add_argument("--output", type=str, default="models/gan")
    parser.add_argument("--per-category", type=int, default=500)
    parser.add_argument("--synthetic-only", action="store_true")
    parser.add_argument("--save-to-db", action="store_true")
    parser.add_argument("--push-to-mlflow", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s [%(name)s] %(message)s",
    )

    config = GANTrainingConfig(
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr_d=args.lr_d,
        output_dir=args.output,
        triplets_per_category=args.per_category,
    )

    if args.synthetic_only:
        triplets = _get_synthetic_triplets()
        logger.info("Using %d synthetic triplets.", len(triplets))
    else:
        # Fetch here so we can save to DB before training
        trainer_tmp = GANTrainer.__new__(GANTrainer)
        trainer_tmp.config = config
        triplets = trainer_tmp.fetch_training_triplets()

    # --- DB: create run and save training data ---
    db = None
    db_run_id = None
    if args.save_to_db:
        try:
            from dotenv import load_dotenv
            load_dotenv()
            from src.database import NeonDB

            db = NeonDB()
            db.initialize_schema()
            db_run_id = db.create_training_run(
                model_type="bert-gan-swap",
                model_name="bert-base-uncased",
                hyperparameters={
                    "epochs": config.epochs,
                    "batch_size": config.batch_size,
                    "lr_d": config.lr_d,
                    "num_triplets": len(triplets),
                },
                notes="BERT GAN with entity-swap generator",
            )
            print(f"DB run_id: {db_run_id}")

            training_data = [
                {"claim": f"{s} | {p} | {o}", "evidence": "", "label": "REAL"}
                for s, p, o in triplets
            ]
            db.save_training_data(db_run_id, training_data)
            print(f"Saved {len(training_data)} triplets to DB")
        except Exception as e:
            print(f"Warning: DB save failed: {e}")
            db = None
            db_run_id = None

    # --- Train ---
    trainer = GANTrainer(config=config, triplets=triplets)
    history = trainer.train()
    final_metrics = history.summary()

    # --- DB: update with metrics ---
    if db and db_run_id:
        try:
            db.update_training_run(
                run_id=db_run_id,
                status="completed",
                num_training_examples=len(triplets),
                metrics=final_metrics,
            )
            print(f"Updated DB run_id {db_run_id} with metrics")
        except Exception as e:
            print(f"Warning: DB update failed: {e}")

    # --- MLflow ---
    mlflow_run_id = None
    if args.push_to_mlflow:
        try:
            mlflow_run_id = _push_gan_to_mlflow(config.output_dir, final_metrics, config)
            print(f"MLflow run_id: {mlflow_run_id}")

            if db and db_run_id:
                db.update_training_run(run_id=db_run_id, mlflow_run_id=mlflow_run_id)
                print(f"Linked DB run_id {db_run_id} <-> MLflow {mlflow_run_id}")
        except Exception as e:
            print(f"Warning: MLflow push failed: {e}")

    # --- Quick evaluation ---
    real_triplets = [
        ("Paris", "is capital of", "France"),
        ("Albert Einstein", "was born in", "Ulm"),
        ("William Shakespeare", "wrote", "Hamlet"),
    ]
    fake_triplets = [
        ("London", "is capital of", "France"),
        ("Albert Einstein", "was born in", "Beijing"),
        ("William Shakespeare", "wrote", "War and Peace"),
    ]
    print("\n--- Discriminator evaluation ---")
    print("REAL:")
    for r in trainer.evaluate_triplets(real_triplets):
        s, p, o = r["triplet"]
        print(f"  {r['score']:.4f}  ({s}, {p}, {o})")
    print("FAKE:")
    for r in trainer.evaluate_triplets(fake_triplets):
        s, p, o = r["triplet"]
        print(f"  {r['score']:.4f}  ({s}, {p}, {o})")

    print(f"\n=== Summary ===")
    print(f"Triplets: {len(triplets)}")
    print(f"Epochs: {config.epochs}")
    print(f"Model: {config.output_dir}")
    if db_run_id:
        print(f"DB run_id: {db_run_id}")
    if mlflow_run_id:
        print(f"MLflow run_id: {mlflow_run_id}")


if __name__ == "__main__":
    main()
