"""BERT-based GAN training pipeline for knowledge-graph fact verification.

Trains a BERTDiscriminator to distinguish real triplets from fakes
generated by swapping entities within the training data.

Usage
-----
    python -m src.gan_trainer --epochs 20 --batch-size 64 --output models/gan
    python -m src.gan_trainer --save-to-db --push-to-mlflow
"""

from __future__ import annotations

import argparse
import logging
import math
import os
import random
import time
from dataclasses import dataclass, field
from typing import Optional

import torch
from transformers import get_cosine_schedule_with_warmup

from factcheck.gan_model import FactGAN
from factcheck.sparql_queries import fetch_mixed_triplets

logger = logging.getLogger(__name__)


# =========================================================================
# Training configuration
# =========================================================================


@dataclass
class GANTrainingConfig:
    lr_d: float = 2e-5
    weight_decay: float = 0.01
    epochs: int = 20
    batch_size: int = 64
    log_every: int = 1
    label_smoothing: float = 0.9

    # Data
    triplets_per_category: int = 5000
    categories: Optional[list[str]] = None

    # Regularization
    freeze_bert_layers: int = 10
    dropout: float = 0.4
    warmup_ratio: float = 0.1

    # Generator mode: "random" (default), "hard_negative", "reinforce"
    generator_mode: str = "random"
    hard_negative_k: int = 5
    lr_g: float = 1e-3  # Learning rate for policy generator (reinforce only)

    # Early stopping
    patience: int = 3
    min_delta: float = 0.001

    # Output
    output_dir: str = "models/gan"
    device: Optional[str] = None


# =========================================================================
# Metrics tracking
# =========================================================================


@dataclass
class EpochMetrics:
    d_loss: float = 0.0
    d_real_score: float = 0.0
    d_fake_score: float = 0.0
    g_loss: float = 0.0
    g_reward: float = 0.0
    num_steps: int = 0

    def update(self, step_metrics: dict) -> None:
        self.d_loss += step_metrics["d_loss"]
        self.d_real_score += step_metrics["d_real_score"]
        self.d_fake_score += step_metrics["d_fake_score"]
        self.g_loss += step_metrics.get("g_loss", 0.0)
        self.g_reward += step_metrics.get("g_reward", 0.0)
        self.num_steps += 1

    def average(self) -> dict[str, float]:
        n = max(self.num_steps, 1)
        avg: dict[str, float] = {
            "d_loss": self.d_loss / n,
            "d_real_score": self.d_real_score / n,
            "d_fake_score": self.d_fake_score / n,
        }
        if self.g_loss != 0.0:
            avg["g_loss"] = self.g_loss / n
            avg["g_reward"] = self.g_reward / n
        return avg


@dataclass
class TrainingHistory:
    epochs: list[dict[str, float]] = field(default_factory=list)

    def append(self, epoch_avg: dict[str, float]) -> None:
        self.epochs.append(epoch_avg)

    def summary(self) -> dict[str, float]:
        return self.epochs[-1] if self.epochs else {}


# =========================================================================
# GANTrainer
# =========================================================================


class GANTrainer:
    """Train BERTDiscriminator on real vs swap-generated fake triplets."""

    def __init__(
        self,
        config: Optional[GANTrainingConfig] = None,
        triplets: Optional[list[tuple[str, str, str]]] = None,
    ) -> None:
        self.config = config or GANTrainingConfig()

        # Fetch data if not provided
        if triplets is None:
            triplets = self.fetch_training_triplets()
        self.triplets = triplets

        self.gan = FactGAN(
            triplets=triplets,
            device=self.config.device,
            freeze_bert_layers=self.config.freeze_bert_layers,
            dropout=self.config.dropout,
            generator_mode=self.config.generator_mode,
        )

        # Only optimize trainable parameters (unfrozen BERT layers + classifier)
        self.optimizer_d = torch.optim.AdamW(
            filter(lambda p: p.requires_grad, self.gan.discriminator.parameters()),
            lr=self.config.lr_d,
            weight_decay=self.config.weight_decay,
        )

        # REINFORCE mode: separate optimizer for the policy generator
        self.optimizer_g: Optional[torch.optim.Optimizer] = None
        if self.config.generator_mode == "reinforce" and self.gan.policy_generator is not None:
            self.optimizer_g = torch.optim.Adam(
                self.gan.policy_generator.parameters(),
                lr=self.config.lr_g,
            )

        self.history = TrainingHistory()

    def fetch_training_triplets(self) -> list[tuple[str, str, str]]:
        triplets: list[tuple[str, str, str]] = []
        logger.info("Fetching training triplets from DBpedia...")
        try:
            triplets = fetch_mixed_triplets(
                per_category=self.config.triplets_per_category,
                categories=self.config.categories,
            )
        except Exception as exc:
            logger.warning("Failed to fetch from DBpedia: %s", exc)

        if not triplets:
            logger.error("No triplets fetched. Check DBpedia connectivity.")

        logger.info("Total training triplets: %d", len(triplets))
        return triplets

    def _evaluate_on(self, triplets: list[tuple[str, str, str]]) -> dict[str, float]:
        """Evaluate discriminator on a set of triplets (real + generated fakes).

        Returns dict with val_loss, val_real_score, val_fake_score, val_accuracy.
        """
        self.gan.discriminator.eval()
        batch_size = self.config.batch_size
        total_loss = 0.0
        total_real = 0.0
        total_fake = 0.0
        correct = 0
        total = 0
        num_batches = 0

        for i in range(0, len(triplets), batch_size):
            batch = triplets[i : i + batch_size]
            if len(batch) < 2:
                continue

            fake_batch = self.gan.generator.generate_fakes(batch)
            real_ids, real_mask = self.gan.discriminator.encode_triplets(batch)
            fake_ids, fake_mask = self.gan.discriminator.encode_triplets(fake_batch)

            with torch.no_grad():
                real_out = self.gan.discriminator(real_ids, real_mask)
                fake_out = self.gan.discriminator(fake_ids, fake_mask)

                real_labels = torch.ones(len(batch), 1, device=real_out.device)
                fake_labels = torch.zeros(len(batch), 1, device=fake_out.device)

                loss = self.gan.criterion(real_out, real_labels) + self.gan.criterion(fake_out, fake_labels)

            total_loss += loss.item()
            total_real += real_out.mean().item()
            total_fake += fake_out.mean().item()
            correct += (real_out > 0.5).sum().item() + (fake_out < 0.5).sum().item()
            total += len(batch) * 2
            num_batches += 1

        n = max(num_batches, 1)
        return {
            "val_loss": total_loss / n,
            "val_real_score": total_real / n,
            "val_fake_score": total_fake / n,
            "val_accuracy": correct / max(total, 1),
        }

    def train(
        self,
        epochs: Optional[int] = None,
        save: bool = True,
    ) -> TrainingHistory:
        num_epochs = epochs or self.config.epochs
        batch_size = self.config.batch_size
        all_triplets = self.triplets

        if not all_triplets:
            logger.error("No training triplets available. Aborting.")
            return self.history

        # 90/10 train/val split
        shuffled_all = list(all_triplets)
        random.shuffle(shuffled_all)
        val_size = max(len(shuffled_all) // 10, batch_size)
        val_triplets = shuffled_all[:val_size]
        train_triplets = shuffled_all[val_size:]

        num_batches = math.ceil(len(train_triplets) / batch_size)

        # Count trainable vs frozen parameters
        trainable = sum(p.numel() for p in self.gan.discriminator.parameters() if p.requires_grad)
        frozen = sum(p.numel() for p in self.gan.discriminator.parameters() if not p.requires_grad)

        logger.info(
            "Starting training: %d epochs, %d batches/epoch, "
            "batch_size=%d, %d train / %d val triplets, "
            "early_stopping patience=%d, frozen_layers=%d, dropout=%.2f",
            num_epochs, num_batches, batch_size,
            len(train_triplets), len(val_triplets),
            self.config.patience, self.config.freeze_bert_layers,
            self.config.dropout,
        )
        logger.info(
            "Parameters: %d trainable, %d frozen (%.1f%% frozen)",
            trainable, frozen, 100.0 * frozen / (trainable + frozen),
        )
        t_start = time.time()

        # LR scheduler: warmup + cosine decay
        total_steps = num_batches * num_epochs
        warmup_steps = int(total_steps * self.config.warmup_ratio)
        scheduler = get_cosine_schedule_with_warmup(
            self.optimizer_d,
            num_warmup_steps=warmup_steps,
            num_training_steps=total_steps,
        )
        logger.info(
            "LR scheduler: cosine with %d warmup steps / %d total steps",
            warmup_steps, total_steps,
        )

        best_val_loss = float("inf")
        epochs_without_improvement = 0
        best_state_dict = None

        for epoch in range(1, num_epochs + 1):
            # --- Train ---
            shuffled = list(train_triplets)
            random.shuffle(shuffled)
            epoch_metrics = EpochMetrics()

            self.gan.discriminator.train()
            for i in range(num_batches):
                start_idx = i * batch_size
                end_idx = min(start_idx + batch_size, len(shuffled))
                batch = shuffled[start_idx:end_idx]
                if len(batch) < 2:
                    continue

                if self.config.generator_mode == "hard_negative":
                    step_metrics = self.gan.train_step_hard_negative(
                        real_triplets=batch,
                        optimizer_d=self.optimizer_d,
                        label_smoothing=self.config.label_smoothing,
                        k=self.config.hard_negative_k,
                    )
                elif self.config.generator_mode == "reinforce":
                    step_metrics = self.gan.train_step_reinforce(
                        real_triplets=batch,
                        optimizer_d=self.optimizer_d,
                        optimizer_g=self.optimizer_g,
                        label_smoothing=self.config.label_smoothing,
                        k=self.config.hard_negative_k,
                    )
                else:
                    step_metrics = self.gan.train_step(
                        real_triplets=batch,
                        optimizer_d=self.optimizer_d,
                        label_smoothing=self.config.label_smoothing,
                    )
                scheduler.step()
                epoch_metrics.update(step_metrics)

            avg = epoch_metrics.average()

            # --- Validate ---
            val_metrics = self._evaluate_on(val_triplets)
            avg.update(val_metrics)
            self.history.append(avg)

            # --- Early stopping ---
            val_loss = val_metrics["val_loss"]
            if val_loss < best_val_loss - self.config.min_delta:
                best_val_loss = val_loss
                epochs_without_improvement = 0
                best_state_dict = {
                    k: v.cpu().clone()
                    for k, v in self.gan.discriminator.state_dict().items()
                }
            else:
                epochs_without_improvement += 1

            # --- Logging ---
            if epoch % self.config.log_every == 0 or epoch == 1:
                elapsed = time.time() - t_start
                fake_examples = step_metrics.get("fake_examples", [])
                real_examples = batch[:3]

                base_msg = (
                    "Epoch %3d/%d | D_loss: %.4f | D_real: %.3f | D_fake: %.3f | "
                    "val_loss: %.4f | val_acc: %.3f | patience: %d/%d | elapsed: %.1fs"
                )
                base_args = [
                    epoch, num_epochs,
                    avg["d_loss"], avg["d_real_score"], avg["d_fake_score"],
                    val_loss, val_metrics["val_accuracy"],
                    epochs_without_improvement, self.config.patience,
                    elapsed,
                ]
                if "g_loss" in avg:
                    base_msg += " | G_loss: %.4f | G_reward: %.3f"
                    base_args.extend([avg["g_loss"], avg["g_reward"]])
                logger.info(base_msg, *base_args)
                for real, fake in zip(real_examples, fake_examples):
                    logger.info("  REAL: %s | %s | %s", *real)
                    logger.info("  FAKE: %s | %s | %s", *fake)

            if epochs_without_improvement >= self.config.patience:
                logger.info(
                    "Early stopping at epoch %d (no improvement for %d epochs).",
                    epoch, self.config.patience,
                )
                break

        # Restore best weights
        if best_state_dict is not None:
            self.gan.discriminator.load_state_dict(best_state_dict)
            logger.info("Restored best model (val_loss=%.4f).", best_val_loss)

        total_time = time.time() - t_start
        logger.info("Training complete in %.1f seconds.", total_time)

        if save:
            self.gan.save(self.config.output_dir)
            logger.info("Model saved to %s", self.config.output_dir)

        return self.history

    def evaluate_triplets(
        self, triplets: list[tuple[str, str, str]]
    ) -> list[dict]:
        scores = self.gan.discriminate_triplets(triplets)
        return [
            {"triplet": t, "score": scores[i].item()}
            for i, t in enumerate(triplets)
        ]


# =========================================================================
# CLI
# =========================================================================


def _push_gan_to_mlflow(output_dir: str, metrics: dict, config: GANTrainingConfig) -> str:
    import dagshub
    import mlflow

    dagshub.init("NLP-Fact-checking", "MarcoSrhl", mlflow=True)
    mlflow.set_experiment("fact-checker")

    run_name = f"gan_swap_ep{config.epochs}"
    with mlflow.start_run(run_name=run_name) as run:
        mlflow.log_artifacts(output_dir, artifact_path="gan_model")
        mlflow.log_params({
            "model_type": "bert-gan-swap",
            "lr_d": config.lr_d,
            "epochs": config.epochs,
            "batch_size": config.batch_size,
            "generator_mode": config.generator_mode,
            "hard_negative_k": config.hard_negative_k,
        })
        if metrics:
            safe = {k: v for k, v in metrics.items() if isinstance(v, (int, float))}
            mlflow.log_metrics(safe)
        mlflow.set_tag("mlflow.note.content", "BERT GAN with entity-swap generator")
        return run.info.run_id


def main() -> None:
    parser = argparse.ArgumentParser(description="Train FactGAN (swap) on DBpedia triplets.")
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--lr-d", type=float, default=2e-5)
    parser.add_argument("--output", type=str, default="models/gan")
    parser.add_argument("--per-category", type=int, default=5000)
    parser.add_argument("--patience", type=int, default=3, help="Early stopping patience (epochs)")
    parser.add_argument("--freeze-bert-layers", type=int, default=10, help="Freeze first N BERT encoder layers (of 12)")
    parser.add_argument("--dropout", type=float, default=0.4, help="Dropout rate for classifier head")
    parser.add_argument("--generator-mode", type=str, default="random",
                        choices=["random", "hard_negative", "reinforce"],
                        help="Generator strategy: random (default), hard_negative, reinforce")
    parser.add_argument("--hard-negative-k", type=int, default=5, help="Number of candidates for hard_negative/reinforce")
    parser.add_argument("--lr-g", type=float, default=1e-3, help="Learning rate for policy generator (reinforce only)")
    parser.add_argument("--save-to-db", action="store_true")
    parser.add_argument("--push-to-mlflow", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s [%(name)s] %(message)s",
    )

    config = GANTrainingConfig(
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr_d=args.lr_d,
        output_dir=args.output,
        triplets_per_category=args.per_category,
        patience=args.patience,
        freeze_bert_layers=args.freeze_bert_layers,
        dropout=args.dropout,
        generator_mode=args.generator_mode,
        hard_negative_k=args.hard_negative_k,
        lr_g=args.lr_g,
    )

    # Fetch here so we can save to DB before training
    trainer_tmp = GANTrainer.__new__(GANTrainer)
    trainer_tmp.config = config
    triplets = trainer_tmp.fetch_training_triplets()

    # --- DB: create run and save training data ---
    db = None
    db_run_id = None
    if args.save_to_db:
        try:
            from dotenv import load_dotenv
            load_dotenv()
            from src.database import NeonDB

            db = NeonDB()
            db.initialize_schema()
            db_run_id = db.create_training_run(
                model_type="bert-gan-swap",
                model_name="bert-base-uncased",
                hyperparameters={
                    "epochs": config.epochs,
                    "batch_size": config.batch_size,
                    "lr_d": config.lr_d,
                    "num_triplets": len(triplets),
                    "generator_mode": config.generator_mode,
                    "hard_negative_k": config.hard_negative_k,
                },
                notes=f"BERT GAN with {config.generator_mode} generator",
            )
            print(f"DB run_id: {db_run_id}")

            training_data = [
                {"claim": f"{s} | {p} | {o}", "evidence": "", "label": "REAL"}
                for s, p, o in triplets
            ]
            db.save_training_data(db_run_id, training_data)
            print(f"Saved {len(training_data)} triplets to DB")
        except Exception as e:
            print(f"Warning: DB save failed: {e}")
            db = None
            db_run_id = None

    # --- Train ---
    trainer = GANTrainer(config=config, triplets=triplets)
    history = trainer.train()
    final_metrics = history.summary()

    # --- DB: update with metrics ---
    if db and db_run_id:
        try:
            db.update_training_run(
                run_id=db_run_id,
                status="completed",
                num_training_examples=len(triplets),
                metrics=final_metrics,
            )
            print(f"Updated DB run_id {db_run_id} with metrics")
        except Exception as e:
            print(f"Warning: DB update failed: {e}")

    # --- MLflow ---
    mlflow_run_id = None
    if args.push_to_mlflow:
        try:
            mlflow_run_id = _push_gan_to_mlflow(config.output_dir, final_metrics, config)
            print(f"MLflow run_id: {mlflow_run_id}")

            if db and db_run_id:
                db.update_training_run(run_id=db_run_id, mlflow_run_id=mlflow_run_id)
                print(f"Linked DB run_id {db_run_id} <-> MLflow {mlflow_run_id}")
        except Exception as e:
            print(f"Warning: MLflow push failed: {e}")

    # --- Quick evaluation ---
    real_triplets = [
        ("Paris", "is capital of", "France"),
        ("Albert Einstein", "was born in", "Ulm"),
        ("William Shakespeare", "wrote", "Hamlet"),
    ]
    fake_triplets = [
        ("London", "is capital of", "France"),
        ("Albert Einstein", "was born in", "Beijing"),
        ("William Shakespeare", "wrote", "War and Peace"),
    ]
    print("\n--- Discriminator evaluation ---")
    print("REAL:")
    for r in trainer.evaluate_triplets(real_triplets):
        s, p, o = r["triplet"]
        print(f"  {r['score']:.4f}  ({s}, {p}, {o})")
    print("FAKE:")
    for r in trainer.evaluate_triplets(fake_triplets):
        s, p, o = r["triplet"]
        print(f"  {r['score']:.4f}  ({s}, {p}, {o})")

    print(f"\n=== Summary ===")
    print(f"Triplets: {len(triplets)}")
    print(f"Epochs: {config.epochs}")
    print(f"Model: {config.output_dir}")
    if db_run_id:
        print(f"DB run_id: {db_run_id}")
    if mlflow_run_id:
        print(f"MLflow run_id: {mlflow_run_id}")


if __name__ == "__main__":
    main()
